networks:
  dev:

services:
  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    networks:
      - dev

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://root:qwerty@mongo:27017/
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URL=mongodb://root:qwerty@mongo:27017/
      - SECRET=2363d042e509c2cf7c1af5b7e47b5db866b81b96130ce30be89919c5617eddcc
    networks:
      - dev
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://192.168.0.107/api
        VITE_API_WS_URL: http://192.168.0.107
    networks:
      - dev
